<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="SE Asia Standard Time">
<General productName="HPE Unified Functional Testing" productVer="14.03" os="" host="H74ZQN2"><DocLocation><![CDATA[C:\uft-samples\open_search_google]]></DocLocation></General>
<Doc rID="T1"   productName= "HPE Unified Functional Testing"  >
<DName><![CDATA[open_search_google]]></DName>
<Res><![CDATA[Res1]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[open google on IE]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Google]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[12/20/2018 - 12:53:38]]></Time>
<TimeTick>1545285218</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Google]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/20/2018 - 12:53:38]]></Time>
<TimeTick>1545285218</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Search.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["qasymphony"]]></Details>
<Time><![CDATA[12/20/2018 - 12:53:38]]></Time>
<TimeTick>1545285218</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="12" Source="open google on IE" SourceLine="-1" >
<Disp><![CDATA[Search.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[lga.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/20/2018 - 12:53:49]]></Time>
<TimeTick>1545285229</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="15" Source="open google on IE" SourceLine="-1" >
<Disp><![CDATA[lga.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Google Search.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/20/2018 - 12:53:49]]></Time>
<TimeTick>1545285229</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="18" Source="open google on IE" SourceLine="-1" >
<Disp><![CDATA[Google Search.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="11" Source="open google on IE" SourceLine="-1" >
<Disp><![CDATA[Google]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="10" Source="open google on IE" SourceLine="-1" >
<Disp><![CDATA[Google]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="12/20/2018 - 12:53:38" eTime="12/20/2018 - 12:53:49" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" >
<Disp><![CDATA[open google on IE Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T10">
<AName><![CDATA[click QASymphony link]]></AName>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[qasymphony - Google Search]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[12/20/2018 - 12:53:50]]></Time>
<TimeTick>1545285230</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[qasymphony - Google Search]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/20/2018 - 12:53:50]]></Time>
<TimeTick>1545285230</TimeTick>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[QASymphonyhttps://www.qasympho.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/20/2018 - 12:53:50]]></Time>
<TimeTick>1545285230</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="26" Source="click QASymphony link" SourceLine="-1" >
<Disp><![CDATA[QASymphonyhttps://www.qasympho.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="25" Source="click QASymphony link" SourceLine="-1" >
<Disp><![CDATA[qasymphony - Google Search]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="24" Source="click QASymphony link" SourceLine="-1" >
<Disp><![CDATA[qasymphony - Google Search]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="12/20/2018 - 12:53:49" eTime="12/20/2018 - 12:53:50" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="20" >
<Disp><![CDATA[click QASymphony link Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T14">
<AName><![CDATA[click Company menu]]></AName>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Software Testing, Test]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[12/20/2018 - 12:53:53]]></Time>
<TimeTick>1545285233</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Software Testing, Test]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/20/2018 - 12:53:53]]></Time>
<TimeTick>1545285233</TimeTick>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Company.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/20/2018 - 12:53:53]]></Time>
<TimeTick>1545285233</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="37" Source="click Company menu" SourceLine="-1" >
<Disp><![CDATA[Company.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="36" Source="click Company menu" SourceLine="-1" >
<Disp><![CDATA[Software Testing, Test]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="35" Source="click Company menu" SourceLine="-1" >
<Disp><![CDATA[Software Testing, Test]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="12/20/2018 - 12:53:50" eTime="12/20/2018 - 12:53:53" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="28" >
<Disp><![CDATA[click Company menu Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T18">
<AName><![CDATA[click Meet our team]]></AName>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[QASymphony - Home of the]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[12/20/2018 - 12:53:55]]></Time>
<TimeTick>1545285235</TimeTick>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[QASymphony - Home of the]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/20/2018 - 12:53:55]]></Time>
<TimeTick>1545285235</TimeTick>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Meet Our Team.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/20/2018 - 12:53:55]]></Time>
<TimeTick>1545285235</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="44" Source="click Meet our team" SourceLine="-1" >
<Disp><![CDATA[Meet Our Team.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="43" Source="click Meet our team" SourceLine="-1" >
<Disp><![CDATA[QASymphony - Home of the]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="42" Source="click Meet our team" SourceLine="-1" >
<Disp><![CDATA[QASymphony - Home of the]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="12/20/2018 - 12:53:53" eTime="12/20/2018 - 12:53:56" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="39" >
<Disp><![CDATA[click Meet our team Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T22">
<AName><![CDATA[close IE]]></AName>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Team - QASymphony]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[12/20/2018 - 12:53:58]]></Time>
<TimeTick>1545285238</TimeTick>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Team - QASymphony]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/20/2018 - 12:53:58]]></Time>
<TimeTick>1545285238</TimeTick>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Team - QASymphony.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/20/2018 - 12:53:58]]></Time>
<TimeTick>1545285238</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="51" Source="close IE" SourceLine="-1" >
<Disp><![CDATA[Team - QASymphony.Sync]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="50" Source="close IE" SourceLine="-1" >
<Disp><![CDATA[Team - QASymphony]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Team - QASymphony.Close All Tabs]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/20/2018 - 12:53:58]]></Time>
<TimeTick>1545285238</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="52" Source="close IE" SourceLine="-1" >
<Disp><![CDATA[Team - QASymphony.Close All Tabs]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="49" Source="close IE" SourceLine="-1" >
<Disp><![CDATA[Team - QASymphony]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="12/20/2018 - 12:53:56" eTime="12/20/2018 - 12:53:59" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="46" >
<Disp><![CDATA[close IE Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" >
<Disp><![CDATA[open_search_google Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="12/20/2018 - 12:53:34" eTime="12/20/2018 - 12:54:00" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" >
<Disp><![CDATA[Test open_search_google Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>